import { createContext, useContext, useEffect, useState } from 'react';
import { Button } from '../design/components/ui/button';

export type OperatorMembership = { id: string; tenantId: string; role: 'viewer' | 'operator' | 'admin' };
export type OperatorSession = {
  user: { id: string; name: string; email: string };
  mustChangePassword: boolean;
  bootstrapCredentialExpiresAt?: string | null;
  installationOwner: boolean;
  memberships: OperatorMembership[];
};

type AuthContextValue = {
  session: OperatorSession;
  refresh: () => Promise<void>;
  signOut: () => Promise<void>;
};

const AuthContext = createContext<AuthContextValue | undefined>(undefined);

export function AuthGate(props: { children: React.ReactNode }): React.ReactElement {
  const [session, setSession] = useState<OperatorSession | null | undefined>(undefined);
  const pathname = window.location.pathname;

  const refresh = async () => {
    const response = await fetch('/operator-api/session', { credentials: 'same-origin' });
    if (response.status === 401) {
      setSession(null);
      return;
    }
    if (!response.ok) throw new Error(`${response.status} ${response.statusText}`);
    const next = await response.json() as OperatorSession;
    setSession(next);
    const allowed = new Set(next.memberships.map((membership) => membership.tenantId));
    const preferred = window.localStorage.getItem('callagent.operator.tenant');
    if (!preferred || !allowed.has(preferred)) {
      const first = next.memberships[0]?.tenantId;
      if (first) window.localStorage.setItem('callagent.operator.tenant', first);
    }
  };

  useEffect(() => {
    void refresh().catch(() => setSession(null));
    const listener = () => { void refresh(); };
    window.addEventListener('callagent:auth-required', listener);
    return () => window.removeEventListener('callagent:auth-required', listener);
  }, []);

  if (pathname.includes('/invitations/accept')) return <InvitationAcceptance />;
  if (pathname.includes('/reset-password')) return <ResetPassword />;
  if (session === undefined) return <CenteredCard title="Loading Observer…" />;
  if (session === null) return <SignIn onSignedIn={refresh} />;
  if (session.mustChangePassword) return <ChangeTemporaryPassword onChanged={refresh} />;

  const signOut = async () => {
    await fetch('/operator-api/auth/sign-out', { method: 'POST', credentials: 'same-origin', headers: { 'content-type': 'application/json' }, body: '{}' });
    setSession(null);
  };
  const value = { session, refresh, signOut };
  return <AuthContext.Provider value={value}>{props.children}</AuthContext.Provider>;
}

export function useAuth(): AuthContextValue {
  const value = useContext(AuthContext);
  if (!value) throw new Error('useAuth must be used inside AuthGate');
  return value;
}

function SignIn(props: { onSignedIn: () => Promise<void> }): React.ReactElement {
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [error, setError] = useState('');
  const [busy, setBusy] = useState(false);
  const submit = async (event: React.FormEvent) => {
    event.preventDefault(); setBusy(true); setError('');
    const response = await fetch('/operator-api/auth/sign-in/email', {
      method: 'POST', credentials: 'same-origin', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ email, password }),
    });
    if (!response.ok) {
      setError(response.status === 401 ? 'Email or password is incorrect.' : await apiError(response));
      setBusy(false);
      return;
    }
    await props.onSignedIn();
  };
  return <AuthCard title="Sign in to Observer" subtitle="Use your named operator account.">
    <form className="grid gap-4" onSubmit={submit}>
      <Field label="Email" type="email" value={email} onChange={setEmail} autoComplete="username" />
      <Field label="Password" type="password" value={password} onChange={setPassword} autoComplete="current-password" />
      {error ? <p className="text-sm text-danger">{error}</p> : null}
      <Button type="submit" disabled={busy}>{busy ? 'Signing in…' : 'Sign in'}</Button>
      <p className="text-xs text-muted-foreground">Password recovery links are generated by the installation owner.</p>
    </form>
  </AuthCard>;
}

function ChangeTemporaryPassword(props: { onChanged: () => Promise<void> }): React.ReactElement {
  const [currentPassword, setCurrentPassword] = useState('');
  const [newPassword, setNewPassword] = useState('');
  const [confirm, setConfirm] = useState('');
  const [error, setError] = useState('');
  const submit = async (event: React.FormEvent) => {
    event.preventDefault(); setError('');
    if (newPassword !== confirm) { setError('New passwords do not match.'); return; }
    const response = await fetch('/operator-api/complete-bootstrap-password', {
      method: 'POST', credentials: 'same-origin', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ currentPassword, newPassword }),
    });
    if (!response.ok) { setError(await apiError(response)); return; }
    await props.onChanged();
  };
  return <AuthCard title="Replace temporary password" subtitle="This password must be changed before Observer can be used.">
    <form className="grid gap-4" onSubmit={submit}>
      <Field label="Temporary password" type="password" value={currentPassword} onChange={setCurrentPassword} autoComplete="current-password" />
      <Field label="New password" type="password" value={newPassword} onChange={setNewPassword} autoComplete="new-password" />
      <Field label="Confirm new password" type="password" value={confirm} onChange={setConfirm} autoComplete="new-password" />
      <p className="text-xs text-muted-foreground">Use 12–128 characters. All other sessions will be revoked.</p>
      {error ? <p className="text-sm text-danger">{error}</p> : null}
      <Button type="submit">Change password</Button>
    </form>
  </AuthCard>;
}

function InvitationAcceptance(): React.ReactElement {
  const token = new URLSearchParams(window.location.search).get('token') ?? '';
  const [details, setDetails] = useState<{ emailHint: string; tenantId: string; role: string; expiresAt: string }>();
  const [name, setName] = useState(''); const [password, setPassword] = useState(''); const [message, setMessage] = useState('');
  useEffect(() => { void fetch(`/operator-api/invitations/inspect?token=${encodeURIComponent(token)}`).then(async (r) => { if (!r.ok) throw new Error(await apiError(r)); return r.json(); }).then(setDetails).catch((e) => setMessage(String(e.message ?? e))); }, [token]);
  const accept = async (event: React.FormEvent) => {
    event.preventDefault(); setMessage('');
    const response = await fetch('/operator-api/invitations/accept', { method: 'POST', credentials: 'same-origin', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ token, name, password }) });
    if (!response.ok) { setMessage(await apiError(response)); return; }
    setMessage('Invitation accepted. You can now sign in.');
  };
  return <AuthCard title="Accept Observer invitation" subtitle={details ? `${details.emailHint} · ${details.tenantId} · ${details.role}` : 'Validating invitation…'}>
    <form className="grid gap-4" onSubmit={accept}>
      <Field label="Display name (new accounts)" value={name} onChange={setName} />
      <Field label="Password (new accounts)" type="password" value={password} onChange={setPassword} autoComplete="new-password" />
      {message ? <p className="text-sm">{message}</p> : null}
      <Button type="submit" disabled={!details}>Accept invitation</Button>
      <a className="text-sm text-primary underline" href="/operator/">Return to sign in</a>
    </form>
  </AuthCard>;
}

function ResetPassword(): React.ReactElement {
  const token = new URLSearchParams(window.location.search).get('token') ?? '';
  const [newPassword, setNewPassword] = useState(''); const [confirm, setConfirm] = useState(''); const [message, setMessage] = useState('');
  const submit = async (event: React.FormEvent) => {
    event.preventDefault();
    if (newPassword !== confirm) { setMessage('Passwords do not match.'); return; }
    const response = await fetch('/operator-api/auth/reset-password', { method: 'POST', credentials: 'same-origin', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ token, newPassword }) });
    setMessage(response.ok ? 'Password changed. Return to sign in.' : await apiError(response));
  };
  return <AuthCard title="Reset Observer password" subtitle="This one-time link expires after one hour.">
    <form className="grid gap-4" onSubmit={submit}>
      <Field label="New password" type="password" value={newPassword} onChange={setNewPassword} autoComplete="new-password" />
      <Field label="Confirm password" type="password" value={confirm} onChange={setConfirm} autoComplete="new-password" />
      {message ? <p className="text-sm">{message}</p> : null}<Button type="submit">Reset password</Button>
    </form>
  </AuthCard>;
}

function AuthCard(props: { title: string; subtitle?: string; children: React.ReactNode }): React.ReactElement {
  return <div className="flex min-h-screen items-center justify-center bg-background p-6"><div className="w-full max-w-md rounded-xl border border-border bg-card p-6 shadow-xl"><p className="text-xs font-semibold uppercase tracking-[0.22em] text-primary">callAgent</p><h1 className="mt-2 text-2xl font-semibold">{props.title}</h1>{props.subtitle ? <p className="mt-1 mb-6 text-sm text-muted-foreground">{props.subtitle}</p> : null}{props.children}</div></div>;
}
function CenteredCard(props: { title: string }): React.ReactElement { return <AuthCard title={props.title}><div /></AuthCard>; }
function Field(props: { label: string; value: string; onChange: (value: string) => void; type?: string; autoComplete?: string }): React.ReactElement { return <label className="grid gap-1.5 text-sm"><span className="font-medium">{props.label}</span><input className="h-10 rounded-md border border-input bg-background px-3" required={props.label.indexOf('(new accounts)') < 0} type={props.type ?? 'text'} value={props.value} autoComplete={props.autoComplete} onChange={(event) => props.onChange(event.target.value)} /></label>; }
async function apiError(response: Response): Promise<string> { try { const body = await response.json() as { message?: string; error?: string }; return body.message ?? body.error ?? `${response.status} ${response.statusText}`; } catch { return `${response.status} ${response.statusText}`; } }
